#!/usr/bin/env python3
"""Run the isolated Swift check app; validation never contacts an Apple TV."""

import argparse
import hashlib
import json
import os
from pathlib import Path
import signal
import subprocess
import sys
import tempfile
import time


def finish_process_group(process):
    """Only clean the new process group owned by this invocation."""
    try:
        os.killpg(process.pid, 0)
    except ProcessLookupError:
        return False
    os.killpg(process.pid, signal.SIGTERM)
    try:
        process.wait(timeout=3)
    except subprocess.TimeoutExpired:
        pass
    # The app may have exited before its helper. Check the group, not just Popen.
    deadline = time.monotonic() + 3
    while time.monotonic() < deadline:
        try:
            os.killpg(process.pid, 0)
        except ProcessLookupError:
            return True
        except PermissionError:
            # Darwin can briefly refuse signals to an exiting orphan. Do not
            # mistake that for successful cleanup or abandon the result report.
            pass
        time.sleep(0.1)
    try:
        os.killpg(process.pid, signal.SIGKILL)
    except ProcessLookupError:
        pass
    process.wait(timeout=3)
    return True


def run_process(command, timeout):
    process = subprocess.Popen(command, start_new_session=True, stderr=subprocess.DEVNULL)
    failure = None
    try:
        if process.wait(timeout=timeout) != 0:
            failure = "checkAppFailed"
    except subprocess.TimeoutExpired:
        failure = "watchdogTimeout"
    except KeyboardInterrupt:
        failure = "interrupted"
    finally:
        try:
            if finish_process_group(process) and failure is None:
                failure = "leftoverProcesses"
        except OSError:
            failure = "cleanupUnverified"
    return failure


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("plan", type=Path)
    parser.add_argument("--run", action="store_true", help="Start playback; otherwise validate local inputs only")
    parser.add_argument("--tv-is-idle", action="store_true", help="Confirm the chosen TV is available for testing")
    parser.add_argument("--local-only", action="store_true", help="Only the bitmap cancellation profile; no TV or Keychain")
    parser.add_argument("--capture", action="store_true", help="Use an approved Apple TV capture configuration")
    parser.add_argument("--prepare", action="store_true", help="With --capture, prepare fixtures without contacting the TV")
    args = parser.parse_args()
    if args.local_only and (args.capture or args.prepare or args.tv_is_idle):
        parser.error("--local-only cannot use capture, fixture preparation or TV authorization.")
    if args.run and not args.tv_is_idle and not args.local_only:
        parser.error("Playback requires --tv-is-idle. Confirm nobody is watching the chosen TV first.")
    if args.prepare and (not args.capture or args.run):
        parser.error("--prepare requires --capture and cannot be combined with --run.")
    project = Path(__file__).resolve().parent.parent
    if args.capture:
        # The documented command must not leave generated bytecode in source.
        sys.dont_write_bytecode = True
        from playback_capture import CaptureError, run_workflow
        try:
            return run_workflow(args.plan.resolve(), project, run=args.run, prepare=args.prepare)
        except (CaptureError, OSError, ValueError):
            print("Invalid or unavailable capture configuration. No playback was started.")
            return 2
    binary = project / ".build/AirCiller Playback Checks.app/Contents/MacOS/AirCiller"
    if not binary.is_file():
        parser.error("Build the isolated candidate first: ./build.sh --playback-checks")
    command = [str(binary), "--validate-only", str(args.plan.resolve())]
    if not args.run:
        return 1 if run_process(command, timeout=15) else 0
    output_root = project / ".build/playback-checks"
    output_root.mkdir(exist_ok=True)
    directory = Path(tempfile.mkdtemp(prefix="run-", dir=output_root))
    report_path = directory / "report.json"
    command = [str(binary), "--run", str(args.plan.resolve()), "--report", str(report_path),
               "--local-only" if args.local_only else "--tv-is-idle"]
    fingerprint = hashlib.sha256(binary.read_bytes()).hexdigest()
    failure = run_process(command, timeout=300 if args.local_only else 1_800)
    try:
        report = json.loads(report_path.read_text())
    except (OSError, ValueError):
        report = {"outcome": "incomplete", "outputVerification": "not_observed", "results": []}
    if failure:
        if failure != "checkAppFailed" or report.get("outcome") not in {"blocked", "inconclusive", "failed"}:
            report["outcome"] = "failed"
        report["launcherFailure"] = failure
    report["binarySHA256"] = fingerprint
    report["cleanExitObserved"] = failure is None
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    report_path.chmod(0o600)
    print(f"{report['outcome']}: {report_path}")
    expected = "local_bitmap_cancellation_passed" if args.local_only else "automated_checks_passed_output_unverified"
    return 0 if report["outcome"] == expected and not failure else 1


if __name__ == "__main__":
    raise SystemExit(main())
