#!/usr/bin/env python3
"""Run the isolated Swift check app; validation never contacts an Apple TV."""

import argparse
import hashlib
import json
import os
from pathlib import Path
import signal
import subprocess
import sys
import tempfile
import time


def finish_process_group(process):
    """Only clean the new process group owned by this invocation."""
    original_error = sys.exc_info()[1]
    observed_group = False
    group_absent = False
    child_reaped = False

    def group_signal(number):
        try:
            os.killpg(process.pid, number)
            return True
        except ProcessLookupError:
            return False
        except PermissionError:
            # EPERM does not prove either existence or successful cleanup.
            return None

    def wait_for_group(deadline):
        nonlocal observed_group, group_absent
        while True:
            # Reap the direct child even if group inspection is denied. A
            # descendant can keep the group alive after this child exits.
            process.poll()
            state = group_signal(0)
            observed_group = observed_group or state is True
            group_absent = state is False
            if group_absent and process.returncode is not None:
                return True
            if time.monotonic() >= deadline:
                return False
            time.sleep(0.05)

    try:
        initial = group_signal(0)
        observed_group = initial is True
        group_absent = initial is False
        if initial is not False:
            sent = group_signal(signal.SIGTERM)
            observed_group = observed_group or sent is True
        if not wait_for_group(time.monotonic() + 3):
            group_signal(signal.SIGKILL)
            # This is still our unreaped Popen child, not an inferred PID or
            # another group. It may remain signalable when killpg returns EPERM.
            if process.poll() is None:
                try:
                    process.kill()
                except (ProcessLookupError, PermissionError):
                    pass
            wait_for_group(time.monotonic() + 3)
    finally:
        # Always wait, including initial ESRCH/EPERM and signal races. If the
        # OS denies all signals, bounded waiting cannot certify cleanup.
        try:
            process.wait(timeout=3)
            child_reaped = True
        except subprocess.TimeoutExpired:
            pass
    if not group_absent or not child_reaped:
        message = "cleanupUnverified"
        if original_error is not None:
            label = str(original_error)
            if len(label) <= 64 and label.isidentifier():
                message += f" (original failure: {label})"
        raise OSError(message) from original_error
    return observed_group


def run_process(command, timeout):
    process = subprocess.Popen(command, start_new_session=True, stderr=subprocess.DEVNULL)
    failure = None
    try:
        if process.wait(timeout=timeout) != 0:
            failure = "checkAppFailed"
    except subprocess.TimeoutExpired:
        failure = "watchdogTimeout"
    except KeyboardInterrupt:
        failure = "interrupted"
    finally:
        try:
            if finish_process_group(process) and failure is None:
                failure = "leftoverProcesses"
        except OSError:
            failure = "cleanupUnverified"
    return failure


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("plan", type=Path)
    parser.add_argument("--run", action="store_true", help="Start playback; otherwise validate local inputs only")
    parser.add_argument("--tv-is-idle", action="store_true", help="Confirm the chosen TV is available for testing")
    parser.add_argument("--local-only", action="store_true", help="Only the bitmap cancellation profile; no TV or Keychain")
    parser.add_argument("--capture", action="store_true", help="Use an approved Apple TV capture configuration")
    parser.add_argument("--prepare", action="store_true", help="With --capture, prepare fixtures without contacting the TV")
    args = parser.parse_args()
    if args.local_only and (args.capture or args.prepare or args.tv_is_idle):
        parser.error("--local-only cannot use capture, fixture preparation or TV authorization.")
    if args.run and not args.tv_is_idle and not args.local_only:
        parser.error("Playback requires --tv-is-idle. Confirm nobody is watching the chosen TV first.")
    if args.prepare and (not args.capture or args.run):
        parser.error("--prepare requires --capture and cannot be combined with --run.")
    project = Path(__file__).resolve().parent.parent
    if args.capture:
        # The documented command must not leave generated bytecode in source.
        sys.dont_write_bytecode = True
        from playback_capture import CaptureError, run_workflow
        try:
            return run_workflow(args.plan.resolve(), project, run=args.run, prepare=args.prepare)
        except (CaptureError, OSError, ValueError):
            print("Invalid or unavailable capture configuration. No playback was started.")
            return 2
    binary = project / ".build/AirCiller Playback Checks.app/Contents/MacOS/AirCiller"
    if not binary.is_file():
        parser.error("Build the isolated candidate first: ./build.sh --playback-checks")
    command = [str(binary), "--validate-only", str(args.plan.resolve())]
    if not args.run:
        return 1 if run_process(command, timeout=15) else 0
    output_root = project / ".build/playback-checks"
    output_root.mkdir(exist_ok=True)
    directory = Path(tempfile.mkdtemp(prefix="run-", dir=output_root))
    report_path = directory / "report.json"
    command = [str(binary), "--run", str(args.plan.resolve()), "--report", str(report_path),
               "--local-only" if args.local_only else "--tv-is-idle"]
    fingerprint = hashlib.sha256(binary.read_bytes()).hexdigest()
    failure = run_process(command, timeout=300 if args.local_only else 1_800)
    try:
        report = json.loads(report_path.read_text())
    except (OSError, ValueError):
        report = {"outcome": "incomplete", "outputVerification": "not_observed", "results": []}
    if failure:
        if failure != "checkAppFailed" or report.get("outcome") not in {"blocked", "inconclusive", "failed"}:
            report["outcome"] = "failed"
        report["launcherFailure"] = failure
    report["binarySHA256"] = fingerprint
    report["cleanExitObserved"] = failure is None
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    report_path.chmod(0o600)
    print(f"{report['outcome']}: {report_path}")
    expected = "local_bitmap_cancellation_passed" if args.local_only else "automated_checks_passed_output_unverified"
    return 0 if report["outcome"] == expected and not failure else 1


if __name__ == "__main__":
    raise SystemExit(main())
